# Generated by Django 5.0.1 on 2024-01-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0003_alter_register_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('child', 'Child')], max_length=10),
        ),
    ]
